<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HP-PC" failures="2" tests="9" name="RetryMultipleTestCases" time="0.106" errors="0" timestamp="19 Oct 2020 14:43:18 GMT">
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test1" time="0.013">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test1" time="0.018">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.MyTest.RetryFailedTestCases.test1(RetryFailedTestCases.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.MyTest.RetryFailedTestCases.test2(RetryFailedTestCases.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.MyTest.RetryFailedTestCases" name="test3" time="0.002"/>
</testsuite> <!-- RetryMultipleTestCases -->
